baseURL = "https://www.martinkaptein.com"
title = "Martin Kaptein"
theme = "elephants"
languageCode = "en-US"
DefaultContentLanguage = "en"
googleAnalytics = "UA-86096566-3"
disqusShortname = "martinkaptein"
twitterUser = "@martinkaptein"
# See /etch/layouts/robots.txt for more control - this config uses sane defaults
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
paginate = 20
disableHugoGeneratorInject = true

[permalinks]
post = "/:slug/"
page = "/:slug/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

########
##KEEP IN MIND
# schema and other header tags hardcoded in custom layouts
########

# fallback settings, better for them to be defined by language
[params]
  sitename = "Martin Kaptein"
  description = "The website and blog of Martin Kaptein."
  RobotsDisallow = ["/dev/"]
  siteTitle = "Martin Kaptein" # Only for meta title tag, this get appended to the page title
  siteAuthor = "Martin Kaptein"
  twitterUser = "@martinkaptein"
  facebookUser = "martin.kaptein" # Only top part of URL


[languages]

[languages.en] 
languageName = "English"
[languages.en.menu]
[[languages.en.menu.main]]
# name = "home"
# title = "home"
# url = "/"
# weight = -110


[languages.nl] 
languageName = "Nederlands"
[languages.nl.params]
# possible param overwrites go here
[languages.nl.menu]
[[languages.nl.menu.main]]
name = "Blog (engels)"
title = "Blog (engels)"
url = "/"
weight = -1
