baseURL = "https://www.martinkaptein.com"
title = "Martin Kaptein"
theme = "tigers"
languageCode = "en-US"
DefaultContentLanguage = "en"
twitterUser = "@martinkaptein"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
paginate = 20
disableHugoGeneratorInject = true

[permalinks]
blog = "/:slug/"
page = "/:slug/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

########
##KEEP IN MIND
# schema and other header tags hardcoded in custom layouts
########

# fallback settings, better for them to be defined by language
[params]
  HomeListAllPages = false
  sitename = "Martin Kaptein"
  description = "The website and blog of Martin Kaptein."
  RobotsDisallow = ["/dev/"]
  siteTitle = "Martin Kaptein" # Only for meta title tag, this get appended to the page title
  siteAuthor = "Martin Kaptein"
  twitterUser = "@martinkaptein"
  facebookUser = "martin.kaptein" # Only top part of URL
  subHeader = 'Pianist, founder of <a href="https://scriabinclub.com/">Scriabin Club</a>'
  footerHTML = '(c) 2020 Martin Kaptein | <a href="/">Home</a> | <a href="/contact/">Contact</a>'
  strNextPage = "next page"
  strPreviousPage = "previous page"
  metaImage = "/images/himalaya_painting.jpg"


[languages]

[languages.en] 
languageName = "English"

[languages.nl] 
languageName = "Nederlands"
[languages.nl.params]
# possible param overwrites go here
subHeader = 'Pianist, oprichter van de <a href="https://scriabinclub.com/">Scriabin Club</a>'
footerHTML = '(c) 2020 Martin Kaptein | <a href="/nl/">Startpagina</a> | <a href="/nl/contact/">Contact</a>'
strNextPage = "volgende pagina"
strPreviousPage = "vorige pagina"
[languages.nl.menu]
[[languages.nl.menu.main]]
name = "Blog (engels)"
title = "Blog (engels)"
url = "/blog/"
weight = 5
