# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Tigers"
license = "MIT"
licenselink = "https://github.com/martinkaptein/tigers/blob/master/LICENSE"
description = "Tigers is a minimal Hugo theme forked from Elephants theme."
homepage = "https://github.com/martinkaptein/tigers/"
tags = ["minimal", "blog", "clean", "simple", "multilingual", "seo", "privacy"]
features = ["blog", "multilingual", "easy", "seo", "privacy"]
min_version = "0.70.0"

[author]
  name = "Martin Kaptein"
  homepage = "https://www.martinkaptein.com/"

# If porting an existing theme
[original]
  name = "Benny Mei"
  homepage = "https://gitlab.com/meibenny/elephants"
  repo = "https://github.com/meibenny/elephants/"
